data = read.csv("C:/Test_route/dsdawh.csv")
View(data)
cov(cdata$height,cdata$weight)
cov(cdata$height,cdata$weight*1000)
plot(cdata$height,cdata$weight)
cor(cdata$height,cdata$weight)
cor(cdata$height,cdata$weight*1000)   #scale independent
View(trees)
cor(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume)
abline(lm(Volume~Girth, trees))
cor(trees)
cdata= read.csv("C:/Test_route/rank correlation.csv")
View(cdata)
cor(cdata$Rintervi, cdata$Raptitut, method = "spearman")
plot(cdata$Rintervi, cdata$Raptitut)
abline(lm(Rintervi~Raptitut, cdata))
cor.test(data$height,data$weight)

#if p-value is less than 0.05 reject null hypothesis, if its greater than 0.05 we reject alternative and accept null (only for 95% confidence)
r1= c(1,2,3,4,5,6,7,8,9)
r2= c(9,8,7,6,5,4,3,2,1)
cor(r1,r2)
df= data.frame(r1,r2)
plot(r1,r2)
df
cor.test(df$r1, df$r2, method = "spearman")
cor.test(cdata$height, cdata$weight)
